title: Shudan Jew
logo: 1776546835515.jpg
description: I am a passionate and driven researcher- with a focus on using bioinformatics to make sense of large and complex biological data sets.

**Loyola University Maryland**  
*BSc in Biohealth, concentration in Biotech and Biopharma*  
*Hauber Research Fellow*  
Supervised by Dr. Cassandra Holbert  

**Institute of Marine and Environmental Technology**  
*Research Assistant*  
Mentored by Anne Baldino and Dr. Tsvetan Bachvaroff 

show_downloads: true
theme: jekyll-theme-minimal
